[terminal]
shell = "/run/current-system/sw/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

# opacity = 0.7
# blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMonoNF"
size = 16

[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]
