theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"
ret = "goto_word"

[keys.normal.space]
o = "file_picker_in_current_buffer_directory"
q = {q = ":quit-all!"}
