theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"
ret = "goto_word"

[keys.normal.space]
q = { q = ":quit-all!" }
space = { "q" = { "q" = ":quit-all" } }
# move/copy line below/above
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
"A-J" = ["extend_to_line_bounds", "yank", "paste_after"]
"A-K" = ["extend_to_line_bounds", "yank", "paste_before"]
# previous/next buffer
H = "goto_previous_buffer"
L = "goto_next_buffer"
