[language-server.ruby-lsp]
command = "mise"
args = ["x", "--", "ruby-lsp"]
config = { diagnostics = true, formatting = true }

[[language]]
name = "ruby"
language-servers = ["ruby-lsp"]
auto-format = true
